version: '3.7'

services:
  movies.ui:
    container_name: movies.ui
    build:
      context: ./frontend
    ports:
      - ${UI_SERVER_PORT}:80
  movies.api:
    container_name: movies.api
    build:
      context: ./backend
      target: production
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    env_file:
      - .env
    networks:
      - webnet

networks:
  webnet:
